[tool.poetry]
name = "local-circuit"
version = "0.1.0"
description = ""
authors = ["Sandro Sgier"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
